export const SCRAPE_INTERVAL_MS = 2*60000; // 2 mins

export const DATA_DIR = './data/'

export const SNAPSHOT_JSON_FILE_PREFIX = 'snapshot';
export const SNAPSHOT_JSON_FILE_SUFFIX = '.json';
export const SNAPSHOT_JSON_FILE_NAME = DATA_DIR + SNAPSHOT_JSON_FILE_PREFIX + SNAPSHOT_JSON_FILE_SUFFIX;

export const AGGREGATED_JSON_FILE_PREFIX = 'aggregated';
export const AGGREGATED_JSON_FILE_SUFFIX = '.json';
export const AGGREGATED_JSON_FILE_NAME = DATA_DIR + AGGREGATED_JSON_FILE_PREFIX + AGGREGATED_JSON_FILE_SUFFIX;

export const AGGREGATED_CSV_FILE_PREFIX = 'aggregated';
export const AGGREGATED_CSV_FILE_SUFFIX = '.csv';
export const AGGREGATED_CSV_FILE_NAME = DATA_DIR + AGGREGATED_CSV_FILE_PREFIX + AGGREGATED_CSV_FILE_SUFFIX;



